version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - path: .env
        required: true
